/* const admin = require('firebase-admin');

const categoriesCollection = admin.firestore().collection('categories');
async function getAllCaegory() {
    try {
      const querySnapshot = await categoriesCollection.get();
      const admins = [];
      querySnapshot.forEach(doc => {
        admins.push(doc.data());
      });
      return admins;
    } catch (err) {
      console.log('Error getting documents', err);
      throw err;
    }
  }

 */
class Category {
constructor(id, name, description, picture, status, item_order , created_date, modified_date) {
    this.id = id; // represents the id generated by the firestore
    this.name = name;
    this.description = description;
    this.picture = picture;
    this.status = status;
    this.item_order = item_order;
    this.created_date = created_date;
    this.modified_date = modified_date;
}
}

module.exports = Category;
